/**
 * The type of (redux) action which dismisses calendar notification.
 *
 * {
 *     type: DISMISS_CALENDAR_NOTIFICATION
 * }
 */
export const DISMISS_CALENDAR_NOTIFICATION = 'DISMISS_CALENDAR_NOTIFICATION';

export const UPDATE_SCREENSHARE_POPUP_STATE = 'UPDATE_SCREENSHARE_POPUP_STATE';

export const START_POWERPOINT_SLIDES = 'START_POWERPOINT_SLIDES';

export const START_POWERPOINT_SLIDES_AS_PRESENTER = 'START_POWERPOINT_SLIDES_AS_PRESENTER';

export const STOP_POWERPOINT_SLIDES_AS_PRESENTER = 'STOP_POWERPOINT_SLIDES_AS_PRESENTER';

export const NEXT_IMAGE = 'NEXT_IMAGE';
export const PREVIOUS_IMAGE = 'PREVIOUS_IMAGE';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const TOGGLE_DROPDOWN = 'TOGGLE_DROPDOWN';
export const SET_IMAGE_INDEX = 'SET_IMAGE_INDEX';
export const UPDATE_AI_NOTES_CONTENT = 'UPDATE_AI_NOTES_CONTENT';
export const UPDATE_AI_NOTES_WINDOW_REF = 'UPDATE_AI_NOTES_WINDOW_REF';
export const UPDATE_MEETING_REAL_NAME = 'UPDATE_MEETING_REAL_NAME';